sudo: required
script:
- sudo docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:xenial /bin/bash build.sh
  $TRAVIS_COMMIT $TRAVIS_BRANCH
after_success:
- wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
- export UPLOADTOOL_SUFFIX=$(printf $TRAVIS_BRANCH | sed 's/master/stable/')
- bash upload.sh out/*
branches:
  except:
  - "/^(?i:continuous.*)$/"
notifications:
  email: false
  slack:
    secure: Pldw8xPDeNy1Dyd/tYbXtdlkPgrinss+OQU+uQShn9pmsA7f4gcd+gLp2p8TA8CFqtsa0bHnnR3t2oFcN530jPxXEVdUC6D8yKLzklmlFwuQkJPHaj0dMsXSrIwp+BlCisJaqI0nR95YB179QTVROHlixmgh3AINXf02IBWoA+6M3v3YCqrayo0zHrm6+Bv5nCN7O8cYO4doq2MHd+h8rrjG4VStYDwdI+wZfymXASJH7nJYameCjLAbN7nic05ydevjQkj3gYEhLL1JSRcsyad2Vr+UCPrB+NEiC6rKV5CkhpgfNqXhQAKvHsS4RsEF3rUEnoAycfzLx3ZYZuv4qNH5oj5I6xVGdh+cK7MlRltUqVhuIIis6BxbhGDncUqTblBMlH14PHRT+xSk2bufSJKZ82kK/GekE8QJo3IGsS1XDl7lShZJtshrr5SNiBBHxM8pHb3HNn27EH81a+px+TcckoYoeSzMNqWfbpweGS1BlF+e8AZdmD0hY34meNFyXOK2ZJn8kYXZSM8CE94//l465tXeZhMxifeGydG6x1tY96fgSCm8torurXzE0QM5xB7KZ2X9MGFADMv6fmml9OiI4XKICMucZ1XdX8lWHbksggMW2XKe8rU6gRfGoahrwKbgGkZwlV3kndZaYVCmCdJx4xSyIvIF5LTiI9VBOOs=
