sudo: required
script:
- sudo docker run --rm -v $(pwd)/:/build/ -w /build/ ubuntu:xenial /bin/bash build.sh
  $TRAVIS_COMMIT $TRAVIS_BRANCH
after_success:
- wget -q https://github.com/probonopd/uploadtool/raw/master/upload.sh
- export UPLOADTOOL_SUFFIX=$(printf $TRAVIS_BRANCH | sed 's/master/stable/')
- bash upload.sh out/*
branches:
  except:
  - "/^(?i:continuous.*)$/"
notifications:
  email: false
  slack:
    secure: lzW2GlVaeUffiQs54hmtZwAs3F1hHjkGZGe1r1CNVoOfpGwF+j1WHStK47/bvjHCSpHZr46OsbZDB0HUgoAAGrqnPzfWV4RhUlTCVTECTtHiVtFHlOyY0JwDWMSRc8pJhNym4NStazrI87P6Du64L2d8ij/hpmmQA99uEsT8dpEAgg4pv54hixiqURLTndFQ1Nujea6GKhOtWG1/X0GCZeMnAGfuBkdlItYsaB6ClJQessMFPe5dk1Ns+xqT+ZfKPALU6P2NzzCBQm0zkeFtuoB8Fz8dLQ6IiJMXh3olIsvBaT7mWyNqg1497surqxjr93DZOceM4Sf+0YWenxf7B9zqcR4yeardPt8nlVHdgaPTubdNdVqn9VkzLd/nIaxaMcii+I3929Jr1YAaiNwEc6wdJDhISJuFBHz5a9nAdwDD3ZQNoeg58VTR5n2F6j4091ejjIfTTKMJZuaAsQWIQR4SKGllYjSBuL3gAVuDXTjwdk4QJeig753caCf7bp0vzamMQcZfb9bNhYxGEizJ/LVjxctIRkUDvuYYePI6LKh16GCtwdwRcGgVyHivAokZQ/ZolCLAmY7tSsb45KYjpj18ykCYB15x0j35246Mtb6/hKNk+6qvH1mh9Ba1rBgsJKxS57NN3PkKCFpJhN6U7G1k58R2XzLUlOvwVmrtWi4=
